homes:
  max-homes:
    default: 2
    plus: 5

  plus-permission: mineacle.plus

  allowed-worlds:
    enabled: true
    worlds:
      - origins
      - world_nether
      - world_the_end

  blocked-worlds:
    - example_blocked_world

  teleport:
    delay-seconds: 5
    cancel-on-move: true

  delete-confirm:
    timeout-seconds: 5

  team-home:
    enabled: true
    banner-slot: 10
    dye-slot: 19
    teleport-delay-seconds: 5
    delete-confirm-timeout-seconds: 5

    allowed-worlds:
      enabled: true
      worlds:
        - origins
        - world_nether
        - world_the_end

    blocked-worlds:
      - example_blocked_world

teams:
  enabled: true
  max-members: 45
  ban-days: 7

tpa:
  enabled: true
  request-timeout-seconds: 60
  teleport-delay-seconds: 5

economy:
  enabled: true
  starting-balance: 0
  currency-symbol: "$"

  pay:
    enabled: true
    minimum: 0.01

baltop:
  enabled: true
  gui-title: "Balance Top"
  entries-per-page: 45

nickname:
  enabled: true
  prefix: "."
  max-length: 15
  allowed-regex: "^[a-zA-Z_0-9&§]+$"
  op-name-color: "#FF80FF"
  default-name-color: "#bbbbbb"

chat:
  enabled: true
  format: "%luckperms_prefix%%mineacle_chat_displayname%&#bbbbbb: &#bbbbbb%message%"

  worlds:
    mode: global
    groups:
      global:
        - world
        - world_nether
        - world_the_end
        - origins

placeholders:
  datetime:
    timezone: "America/Chicago"
    date-format: "MM/dd/yy"
    time-format: "hh:mm"
    datetime-format: "MM/dd/yy | hh:mm"