name: MineacleCore
main: net.mineacle.core.Core
version: 1.0.0
api-version: "1.21"
author: Mineacle

commands:
  home:
    description: Open your homes menu
    aliases: [homes]
    permission: mineaclehomes.use

  sethome:
    description: Set a named home
    permission: mineaclehomes.use

  delhome:
    description: Delete a named home
    permission: mineaclehomes.use

  renamehome:
    description: Rename a saved home
    permission: mineaclehomes.use

  mineaclehomes:
    description: Reload homes config
    permission: mineaclehomes.admin

  team:
    description: Create, join, and manage your team
    permission: mineacleteams.use

  tpa:
    description: Request to teleport to a player
    permission: mineacletpa.use

  tpahere:
    description: Request a player teleport to you
    permission: mineacletpa.use

  tpaccept:
    description: Accept a teleport request
    permission: mineacletpa.use

  tpdeny:
    description: Deny a teleport request
    permission: mineacletpa.use

permissions:
  mineaclehomes.use:
    default: true

  mineacle.plus:
    default: false

  mineaclehomes.admin:
    default: op

  mineacleteams.use:
    default: true

  mineacleteams.admin:
    default: op

  mineacletpa.use:
    default: true

  mineacletpa.admin:
    default: op